# Generated by Django 4.2 on 2023-06-09 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='label',
            options={'verbose_name': 'Метка'},
        ),
        migrations.AlterField(
            model_name='label',
            name='label_name',
            field=models.CharField(
                error_messages={
                    "unique": '%(model_name)s с таким именем уже существует.'
                },
                max_length=250,
                unique=True,
                verbose_name='Имя'),
        ),
    ]
