# Generated by Django 4.2 on 2023-06-05 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('statuses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('labels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID'
                )),
                ('name', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name='task_author_user',
                    to=settings.AUTH_USER_MODEL
                )),
                ('executor', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name='task_executor_user',
                    to=settings.AUTH_USER_MODEL
                )),
                ('labels', models.ManyToManyField(to='labels.label')),
                ('status', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    to='statuses.status'
                )),
            ],
        ),
    ]
