# Generated by Django 4.2 on 2023-06-05 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.CharField(default=None, max_length=1000),
            preserve_default=False,
        ),
    ]
