# Generated by Django 4.2 on 2023-06-09 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('labels', '0002_alter_label_options_alter_label_label_name'),
        ('tasks', '0005_alter_task_executor_alter_task_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='executor',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='task_executor_user',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Исполнитель'),
        ),
        migrations.AlterField(
            model_name='task',
            name='labels',
            field=models.ManyToManyField(
                to='labels.label',
                verbose_name='Метка'),
        ),
    ]
