# Generated by Django 4.2.1 on 2023-06-26 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_alter_task_executor_alter_task_labels'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['id']},
        ),
    ]
