# Generated by Django 4.2 on 2023-06-09 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0002_alter_status_status_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Статус'},
        ),
        migrations.AlterField(
            model_name='status',
            name='status_name',
            field=models.CharField(error_messages={'unique': '%(model_name)s с таким именем уже существует.'}, max_length=250, unique=True, verbose_name='Имя'),
        ),
    ]
