# Generated by Django 4.2.1 on 2023-06-26 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0003_alter_status_options_alter_status_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(error_messages={'unique': 'Task status с таким Имя уже существует'}, max_length=250, unique=True, verbose_name='Имя'),
        ),
    ]
